- platform: command_line
  switches:
    garage_door:
      command_on: "/usr/bin/curl -X GET http://192.168.1.9:7474/code/garagedoor"
      command_off: "/usr/bin/curl -X GET http://192.168.1.9:7474/code/garagedoor"
      command_state: "/bin/cat /tmp/garagedoorstatus"
      value_template: '{{ value == "on" }}'
    garage_door_set_switch:
      command_on: "/bin/echo on > /tmp/garagedoorstatus"
      command_off: "/bin/echo off > /tmp/garagedoorstatus"
      command_state: "/bin/cat /tmp/garagedoorstatus"
      value_template: '{{ value == "on" }}'

# Garage
- platform: broadlink
  host: 192.168.1.6
  mac: 'B4:43:0D:AA:81:8C'
  type: rm2
  switches:
    b_garagedoor:
      command_on: '1wDNAQYEBAgEBgQJCwQEBAgGCwQTBA8EDwQGBQQECwYMEwUIBAwJGwUGBQQIChcECQQEBAQECAQEDQcEBgQFBQQEBAQNBAUEBAsECwcTDw0HBwQRBQQGBwUEBAsFDgQEBAQECQQEFAQIBAQEBAoRBAQEDgcEBAQMBQQGBBEHDwQFBBAEEAcEBAcREQoICwQECA0ECAcIBg4ZBAkEBBEEBAoEGQ8EBA0ECAcJBgQRDQQEBwQFBCdeBD0knSRAIaEhoiAAAQIioSGhIaEhoSJAIQABAiFBIQABAiKgIaEiQSEAAQEknSQ/IqAiAAEBIz4kAAG3CSaeI54kPiSgIp8k/ySeJpwlniSeJTwl/yQ9JP8mnCadJT0k/ySfIz0lniX+JT0kAAFYBBYUBAUGCwUHBAQMKJwmnSQ+JJ8kniX9Jp0kniSeJJ8kPST/JT0k/iaeJJ0lPCf9JJ4lPCWeJv0mPCQAAYkOBgQIBggHBCacJZ4kPSWdJZ4k/ySeJZ0mnCacJj0k/iQ/I/8knSacJjwl/ySdJT0kniT/JD4kAAFwBB0FKiacJp0lPSWdJJ4l/iWfI50lnSUAATEECgQbBQQFCwQIBAQEBBoPEQQQBQQIAAXcBgUEBAsGDBMFCAQ='
      command_off: '1wDNAQYEBAgEBgQJCwQEBAgGCwQTBA8EDwQGBQQECwYMEwUIBAwJGwUGBQQIChcECQQEBAQECAQEDQcEBgQFBQQEBAQNBAUEBAsECwcTDw0HBwQRBQQGBwUEBAsFDgQEBAQECQQEFAQIBAQEBAoRBAQEDgcEBAQMBQQGBBEHDwQFBBAEEAcEBAcREQoICwQECA0ECAcIBg4ZBAkEBBEEBAoEGQ8EBA0ECAcJBgQRDQQEBwQFBCdeBD0knSRAIaEhoiAAAQIioSGhIaEhoSJAIQABAiFBIQABAiKgIaEiQSEAAQEknSQ/IqAiAAEBIz4kAAG3CSaeI54kPiSgIp8k/ySeJpwlniSeJTwl/yQ9JP8mnCadJT0k/ySfIz0lniX+JT0kAAFYBBYUBAUGCwUHBAQMKJwmnSQ+JJ8kniX9Jp0kniSeJJ8kPST/JT0k/iaeJJ0lPCf9JJ4lPCWeJv0mPCQAAYkOBgQIBggHBCacJZ4kPSWdJZ4k/ySeJZ0mnCacJj0k/iQ/I/8knSacJjwl/ySdJT0kniT/JD4kAAFwBB0FKiacJp0lPSWdJJ4l/iWfI50lnSUAATEECgQbBQQFCwQIBAQEBBoPEQQQBQQIAAXcBgUEBAsGDBMFCAQ='
    garage_light:
      friendly_name: "Garage Light"
      command_on: '6XAkABAGBgoKCwYFCwoFBQYFCgsFBQYGCgoLBgUGBQYFCgYFBgUFBgAAAAA='
      command_off: '6XAkABAGBgoKCwYFCwoFBQYFCgsFBQYGCgoLBgUGBQYFCgYFBgUFBgAAAAA='

# My's room
- platform: broadlink
  host: 192.168.1.7
  mac: 'B4:43:0D:AA:36:B5'
  type: rm2
  switches:
    frontporch:
      friendly_name: "Front Porch Light"
      command_on: '6XMkABAGBQsKCwUFCgsFBQYFCwoGBQUGCgoLBgUGBQoGBQYFBgUGBgAAAAA='
      command_off: '6XMkABAGBQsKCwUFCgsFBQYFCwoGBQUGCgoLBgUGBQoGBQYFBgUGBgAAAAA='
    kitchen_light:
      friendly_name: "Kitchen Light"
      command_on: '6XQiABAGBQoKCgUGCgsFBQYFCwoFBgUFCwoKBgULCgoGBQUFBQYAAAAAAAA='
      command_off: '6XQiABAGBQoKCgUGCgsFBQYFCwoFBgUFCwoKBgULCgoGBQUFBQYAAAAAAAA='
    myrianes_room:
      friendly_name: "Myriane's room Light"
      command_on: '6XAmABAGBgoLBQYKBgUKCgYFBgUGBQoKBgYGBgoGBQUFBgULBgQGBQYFAAA='
      command_off: '6XAmABAGBgoLBQYKBgUKCgYFBgUGBQoKBgYGBgoGBQUFBgULBgQGBQYFAAA='
    zap1:
      command_on: '6QAMAQ4KBBYEFQ4KDwkEFQQWDgkPCQS6BBQRBwQUDwkEFA8IBBUPCAQVDwgEFQ8IBBUPCAQVDwgEFAQUEAgQCAQUBBQQCBAIBLoFExAIBBMRBwUTEAkEEhEHBBQRBwQUEAcEFBAIBBMRBwQVBBMRCQ8JBBMEFBEGEQcFuAYSEQgEExEHBRQPBwUTEQcFEhMFBhIRBwUTEAcGEhEHBRIFFBAHEQgEEgUUEAcRCAS4BhITBQUTEQYGEhEHBhIRBwYREQcFExEHBRIRBwUTEQcFEgUTEgYQOw0HEQcFuAYSEgcEFBAGBhIRBwUSEgYHEREHBRMSBgUSEgYFExEGBhMFEhEHEQcFEgYSEQcRBgYABdwAAAAAAAAAAAAAAAA='
      command_off: '6QAmAQkOFQQJDxQECBATBAgQFAQHERMEBxETBQcREgYGEQcREgYTBRIGEQcFEwUSBrcGFBEGBRISBgUSEwUGExAHBRMRBgYSEQcFExAHBRMRCAUSBBQQCBAHEAgQCAQUBBQEuwQUEQYFExAJBBQQCAQUEQkEFA8JBFEECQQVDwoEFAQVDwsMCw0KDgoEFAQUBLoEFA8JBRQOCAQUDwkEFBAKBBQPCQQUEAkEFBAIBBQQCAQUBBQQCBAKDwcPCQQUBBQEuQUTEQcEFBAHBRMQCAQUEAgEFBAIBBQQBwUUDwgFExAJBBQEFBAIEAcRBxAIBBQFEgW5BRISBgYSEQcFExEGBxERBwUTEQcEFRAGBRMRBwQUEAcFEwUTBBQEEwYSBRIGEgUTBQAF3AAA'
    zap2:
      command_on: '6QCOAhEKCwsECQgHFQQKDhUECRAJDwkQFAQIERQFBhITBQcRFAUTBhIFBxIHEwUSCBATBhIGBrwHEgcRCBATBgYSEwYHEQYSBxETBgcSEgYHERIGBxISBhIHEgcFEgYTBhIHERIHEgYGvgYRBhIHEhIGBhMSBgYSBhMGExEGBhMTBQYSEwYFExMGEgYSBwUTBRMFEwYTEgYSBwW9BhMFEwYSEgcFExIHBRMFEwUUEQcFFBAIBBQRCAQUEQcRCBAIBBUEFAQVBBQQCQ8JBL8FFQQTBBUPCQQVEAkEFQQVBRQPCQQXDgkEFg4KBBUPCRAJDwkEFQQVBBYEFRAJDwkEvwUUBBUFEhEIBBQQCQQVBBQFExEIBBUPCQQVEAgEFRAIEAkQCAQUBBQFFQQUEAoPCAS+BRMGEwUTEQkEFBIGBhMEFAUTEQgFExEHBRQRCQQTEQgRBxEIBhIFEwUUBRMRBxEIBL4GEgYTBRQRBwUTEQgGEgUTBRUQBwUTEQgFExEIBBQRBxIGEQgFFAQVBBMGExIGEgkEvgYSBhMGExEHBRQRBwUTBRMGExIGBxMQBwUTEQcGEhIIEAgRCAQUBBQFEwcREgcRBwW9BhIHEgYTEQcGFBAHBhIGEwUSEgcFExIHBRMTBQYTEQcSBhIIBBMGEwUTBhITBhEHBb0HEwUSCBATBgYSEgcGEgYTBRMSBgYTEQgFEhIHBRMSBhIHEgYGEwUTBhIGEhIHEgYGvgUSBxIGEhIHBhITBQYSBhMGFBAHBRMSCAQTEgcFEhMGEgYSBwUTBhIGEwYSEggQCAS+BhIGEgcREwYGEhMGBhIGEwUTEwUGEhMGBhISBwUTEgYGEwYTBRMFEwYSBhIGFAUSBgAF3BEHBRQRBwUTBRM=' 
      command_off: '6QCUAQ4EBAcNBBMNFwQIDxYECRAJEAgQFAUIEBQECBAVBAcSEwUTBRQEBxIHEhIGEgYGEwYSBr0GEgcRBxETBgcREwYGEgcRBxISBgYSEwYGEhMGBhITBRMGEwUGEwUTEgYSBwUTBhMFvQYSBhMHEhEIBhETBgUSBhMGEhIHBRMSBgYTEgYGEhIHEgcRBwUTBRMTBhIGBRQFEwW9BhMGEgYTEQcGEhIHBRMFFAUTEQgEFRAHBRUPCQQTEQgSBxAIBBUEFRAJDwkEFQQXBL8EFAQVBBQQCAQVEAgEFQQVBBUQCQQVDwoEFQ8KBBYPCQ8KDwkEFwQTEQgPCgQWBBUEvgUUBBQEFBEHBRQRCQQVBBUEFBEIBRMQCAUUEAkEFQ8IEAgRCAQUBhISBxAIBBUEFAS/BRQEEwUTEgcFExEIBBQFEwUVEQYFFBEHBBQRBwUVEAcRCBIGBRQEFRAHEQcFFAUTBr0FEwYTBhIRBwYSEgcFEwUUBRMSBwYSEgYGExEHBRMSBwUTBRMGEgYTBhIGEwYSBRMHAAXcAAAAAA=='
    zap3:
      command_on: '6RAyAAcTBxIHExMGBxMTBwcTBhMHExMHBxMTBwYTEwcSBxMHBhQGFAcSBxIHEwcTEwgSBwa+AAAAAAAA'
      command_off: '6Q8yAAcSBxMHEhMHBxMTBwcTBhMHExMHBxMTBwYTEgcTBxIIBhQGEwcTBxMTBxIHBhQGFAe+AAAAAAAA'
    zap4:
      command_on: '6QD7AQYEBAQXBgQPCgwNFgQKDxUECQ8IEAkQFAQUBRMFCBETBQcRFAUHEQcRBxIHEQcRBxITBhIGBr0HEQgQBxEUBQcREwYHEQcRBxIUBRIHEQcGERMHBRITBgYSBxMFEgYSBxIGEhIGEwcFvAcTBRIGEhMGBhMSBgYSBhIHEhMFEgcSBgYSEggFEhIHBRMGEgYTBRQFEgYTEwUTBgW+BRMGEgYUEQYGEhIIBRIGEwUTEggQBxEIBBMSCAQTEgcEFAUUBRQEFAQVBBMRCBAIBL8FEwUUBBUQBwUVDwgFEwUUBBQRCBAJDwoEFBAJBBYOCgQWBBUEFQQVBBYEFBAJDwkEvwQUBBUEFBAIBBUQCAQVBBUEFBAJEAgRCAQVDwgEFRAIBBQEFQQUBBQFEwUUEQcRCAS+BRQFEwUTEwYFFBAIBBQEFAcREgcRBxEIBBQSBwQUEQgEFAQUBRQEFAUUBRISBxEHBb4GEgcRBhMTBQYTEQcFEwYUBBMSBxEHEQkEExIGBRMSCAQTBxIFEwYSBhQEExIHEQcFvQcSBhIHEhIGBhMRBwUTBhMGEhIHEQcSBgcSEQcGEhIHBRMGFAQTBRQFEgcSEwUSBwW9BxIGEgYTEwUGExIGBxEGEgYTEgYSBxIGBhMRBwYTEQcFEwYSBhMGEwUSBhMSBgwNBQAF3BMSBgYSBhIHEhMFEgc='
      command_off: '6Q0yAAcTBxMHEhMGBxMSBwYUBhMGExMHEwcSBwYUEwcGFBIHBhMGEwcTBxMSBxIHBhQGEwa+AAAAAAAA'
    workbench:
      command_on: '6Q4yAAcTBxMIEhMHBhMTBgcTBhMHExMHBhMTBxMHEgcHExMHBhMGEwYTBhQGEwYTEwcTBwa+AAAAAAAA'
      command_off: '6RAyAAcSCBIIExMGBxMTBwYTBxMHEhMHBxMTBxMGEwcGExMHBxIHEwcSBxMTBxMHBxMGEwe+AAAAAAAA'
    zap_all:
      command_on: '6QDEAQQUBBUEFREHBBUPCQQWBBYEFQ8JBBUPCgQWDwkEFRAJBRQEFRAJDwkEFgQVEAkPCQTABRQEFQQTEwcEFBAIBRMFFAUUEAgGEhMIBBMSBwQUEgcEFQQUEQcRCAUUBBQRBxEIBMEEEwUTBhMRBwUUEQcFFQQTBRQRBwUUEQcFFBEHBRQRBwUUBRMRCREGBhMEFBEIEQgEvgcTBRMFFBEGBxISBwUTBRQFFBEGBhMSBwUTEQgFExMGBRMFExIIEQgEFAQUEQcRCQS+BhIGEwYSEwYGFBEGBhIGEwYSEgcFExIIBBQRBwUTEwcEEwYTEgcRBwUTBhMSBhIHBr0IEQYSBxISBgYTEgcFEwYSBhQRBgYTEwUGExIGBhQRBgYTBhISBxIGBhMFExIHEgYHvQYUBRIGEhMGBhITBwUTBxEGEhMGBhITBgYUEAcGExEHBhIHEhIHEQcGEgYTEwcQBwW+BxIGEgcSEgYHEhIHBxEGEgYTEgcGEhIGBhMSBgYTEgYGEwYTEgcRBgYTBxESBxIGB70GEwYTBhETBggREwUGEwYSBhITBgYTEgYGExMFBhMSBgYSCBEHEQYTBhIGFAUSBhMGAAXcBBURBw=='
      command_off: '6QCCAhYECQ8JEQgPFQUHEBUFBxAVBAgQFAUHEQgRFAQUBRUEFAYGEgYSB7wIEQcRCBEUBAkQFAQIEgcRBhITBQcSEwUIEhIFBxIUBAcSBhMSBhMFEwcRBgcSBxEHvQcTBRIHERMGBhITBgYSBxIGExIGBhMSBgYSFAUGEhQFBhIGExIGEwYSBhIHBhIGFAW9BxIGEwUTEgcGEhIGBhMGEgYTEgYGExIHBRMSBgYTEgYHEgYSEgcSBxEHEQcGEwUTBb8GEgYTBhISBwUTEgcFEwYTBhMRCAQTEQkEFBAIBRQSBgQVBRMRBxEJEAoNCgQVBBYEwAQUBBUEFRAIBBQQCQQWBBUEFg8KBBYPCQQWDwkEFg8JBBQEFRAJDwkQCBAKBBUEFQTABRMGFAQTEQgEFBEIBBYEFAUTEQgEFBEIBBQRCAQUEQgEFAUUEAgRCBAKDwgEFAUTBcAEEwYTBRMSCAQTEgcGEwYSBRMSBwYTEQgFEhEIBRMSCAQUBRMRBxIHEQcRCAUUBBQFvgYSBhMGEhIHBhMRBwUUBRMGEhIHBhMRBwUTEgcFFRAHBRMGExEHEgcRBxIHBxEGEwW+BxIGEgYTEgYGExIIBRMFEgYTEgcGEhIIBBMSBgYTEggEEwUTEgcSBhIHEQgFFAQUBr0GEwYRBxITBgYSEgcGEgcSBhISBwUUEQcFExIHBRMSBwYSBxMRBhIHEgYSBwUTBhMHvAcRBxIHEhIGBhMSBgYTBhIGFBEGBhMSBgYTEwUGExIGBxIGEhIIEQYSBxIHBhIFEwa+BhIHEgYTEgYGEhMGBhIGEwYSEgcGFBEGBhQQBwYSEgcHEQYUEQYSBxIHEQcGEwUTBgAF3AUUBBQFvg=='

# Upstair
- platform: broadlink
  host: 192.168.1.8
  mac: 'B4:43:0D:EE:F5:96'
  type: rm2
  switches:
    masterbath_light:
      friendly_name: "Masterbath Light"
      command_on: '6XQmABAGBQoKBgULBQULCgYFBgUGBQoLBgUGBQsGBQcECgYFBgUGBQUGAAA='
      command_off: '6XQmABAGBQoKBgULBQULCgYFBgUGBQoLBgUGBQsGBQcECgYFBgUGBQUGAAA='
